import { AppLanguage } from './types';

export const TRANSLATIONS = {
  [AppLanguage.ENGLISH]: {
    appName: 'ACS PDF WALA',
    home: 'Home',
    tools: 'Tools',
    settings: 'Settings',
    login: 'Login',
    logout: 'Logout',
    welcome: 'Welcome',
    email: 'Email Address',
    password: 'Password',
    signIn: 'Sign In',
    compressPdf: 'Compress PDF',
    mergePdf: 'Merge PDF',
    imageToPdf: 'Image to PDF',
    splitPdf: 'Split PDF',
    ocrScanner: 'AI OCR Scanner',
    cameraToPdf: 'Camera to PDF',
    bgRemover: 'Remove Background',
    resizeImage: 'Resize Image',
    processing: 'Processing...',
    success: 'Success!',
    error: 'Something went wrong',
    selectFiles: 'Select Files',
    noFilesSelected: 'No files selected',
    download: 'Download',
    share: 'Share',
    darkMode: 'Dark Mode',
    language: 'Language',
    compressDesc: 'Reduce file size',
    mergeDesc: 'Combine multiple PDFs',
    imageToPdfDesc: 'Photos to Document',
    splitDesc: 'Extract pages',
    ocrDesc: 'Extract text with Gemini',
    cameraDesc: 'Scan documents',
    bgRemoverDesc: 'AI Background Removal',
    resizeDesc: 'Change dimensions',
    convert: 'Convert',
    clear: 'Clear',
    pageRange: 'Page Range (e.g., 1-3, 5)',
    quality: 'Quality',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    compressNow: 'Compress Now',
    originalSize: 'Original Size',
    compressedSize: 'Compressed Size',
    saved: 'Saved',
    compressionLevel: 'Compression Level',
    compressing: 'Compressing PDF...',
    analyzing: 'Analyzing pages...',
    capture: 'Capture',
    done: 'Done',
    retake: 'Retake',
    width: 'Width (px)',
    height: 'Height (px)',
    maintainAspectRatio: 'Maintain Aspect Ratio',
    resize: 'Resize',
    removeBg: 'Remove Background',
    removingBg: 'Removing background...',
    downloadApp: 'Download App',
  },
  [AppLanguage.HINDI]: {
    appName: 'ACS PDF वाला',
    home: 'होम',
    tools: 'टूल्स',
    settings: 'सेटिंग्स',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    welcome: 'स्वागत है',
    email: 'ईमेल पता',
    password: 'पासवर्ड',
    signIn: 'साइन इन',
    compressPdf: 'PDF कंप्रेस करें',
    mergePdf: 'PDF जोड़ें',
    imageToPdf: 'फोटो से PDF',
    splitPdf: 'PDF अलग करें',
    ocrScanner: 'AI OCR स्कैनर',
    cameraToPdf: 'कैमरा से PDF',
    bgRemover: 'बैकग्राउंड हटाएं',
    resizeImage: 'इमेज रिसाइज',
    processing: 'प्रक्रिया जारी है...',
    success: 'सफल!',
    error: 'कुछ गलत हो गया',
    selectFiles: 'फाइल चुनें',
    noFilesSelected: 'कोई फाइल नहीं चुनी गई',
    download: 'डाउनलोड',
    share: 'शेयर',
    darkMode: 'डार्क मोड',
    language: 'भाषा',
    compressDesc: 'फाइल साइज कम करें',
    mergeDesc: 'कई PDF को मिलाएं',
    imageToPdfDesc: 'फोटो को डॉक्यूमेंट बनाएं',
    splitDesc: 'पेज निकालें',
    ocrDesc: 'Gemini से टेक्स्ट निकालें',
    cameraDesc: 'डॉक्यूमेंट स्कैन करें',
    bgRemoverDesc: 'AI बैकग्राउंड हटाएं',
    resizeDesc: 'साइज बदलें',
    convert: 'बदलें',
    clear: 'साफ़ करें',
    pageRange: 'पेज नंबर (जैसे 1-3, 5)',
    quality: 'गुणवत्ता',
    low: 'कम',
    medium: 'मध्यम',
    high: 'उच्च',
    compressNow: 'कंप्रेस करें',
    originalSize: 'असली साइज',
    compressedSize: 'नया साइज',
    saved: 'बचत',
    compressionLevel: 'कंप्रेशन लेवल',
    compressing: 'PDF कंप्रेस हो रहा है...',
    analyzing: 'पेज स्कैन हो रहे हैं...',
    capture: 'फोटो लें',
    done: 'हो गया',
    retake: 'दोबारा लें',
    width: 'चौड़ाई (px)',
    height: 'ऊंचाई (px)',
    maintainAspectRatio: 'आस्पेक्ट रेश्यो रखें',
    resize: 'रिसाइज करें',
    removeBg: 'बैकग्राउंड हटाएं',
    removingBg: 'बैकग्राउंड हट रहा है...',
    downloadApp: 'ऐप डाउनलोड करें',
  },
};